// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkSMQHIxDcNWy4nxeVSSJeQoBrEV1gJ5Q',
    appId: '1:1007384718308:web:bcbdf3358b38d748c7f5f1',
    messagingSenderId: '1007384718308',
    projectId: 'taskmonitor-df458',
    authDomain: 'taskmonitor-df458.firebaseapp.com',
    storageBucket: 'taskmonitor-df458.firebasestorage.app',
    measurementId: 'G-9RJ5J52CWK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYHUCcDO2mI72BhfmVbmCfH6IirFNDOzA',
    appId: '1:1007384718308:android:5c7b3513599966f1c7f5f1',
    messagingSenderId: '1007384718308',
    projectId: 'taskmonitor-df458',
    storageBucket: 'taskmonitor-df458.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1mT_eHyjgmqtBt951XH5T3xedfphjmQ8',
    appId: '1:1007384718308:ios:0fd9f6dc4ad59f4fc7f5f1',
    messagingSenderId: '1007384718308',
    projectId: 'taskmonitor-df458',
    storageBucket: 'taskmonitor-df458.firebasestorage.app',
    iosClientId: '1007384718308-qmb8libnbv05sv7dodmpjp2mkfl3l913.apps.googleusercontent.com',
    iosBundleId: 'com.example.monitoringApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1mT_eHyjgmqtBt951XH5T3xedfphjmQ8',
    appId: '1:1007384718308:ios:0fd9f6dc4ad59f4fc7f5f1',
    messagingSenderId: '1007384718308',
    projectId: 'taskmonitor-df458',
    storageBucket: 'taskmonitor-df458.firebasestorage.app',
    iosClientId: '1007384718308-qmb8libnbv05sv7dodmpjp2mkfl3l913.apps.googleusercontent.com',
    iosBundleId: 'com.example.monitoringApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkSMQHIxDcNWy4nxeVSSJeQoBrEV1gJ5Q',
    appId: '1:1007384718308:web:c500b20422fa27fdc7f5f1',
    messagingSenderId: '1007384718308',
    projectId: 'taskmonitor-df458',
    authDomain: 'taskmonitor-df458.firebaseapp.com',
    storageBucket: 'taskmonitor-df458.firebasestorage.app',
    measurementId: 'G-1LD540S9GR',
  );
}
